original/ulm.geojson

This PR updates ulm geojson.
I manually added missing parking lots and added public_urls for all lots.
However, two questions came up:
* `ulm.get_lot_infos()` currently returns the `v1` lot infos, hence overwriting manual edits like this one. Should I request, as long as `v1` is not phased out, an equivalent pull to the upstream repo? Shouldn't in this case this repo better not contain `ulm.geojson`?
* Ulm's public_url page https://www.parken-in-ulm.de/ declares different capacities than the detail pages of the lots itself, e.g "Am Rathaus" shows `575` vs `580` (see screenshot below). What causes the difference, what should be the official capacity?

Update ulm geojson

---

original/zuerich.geojson

This PR adds missing capacities and coordinates for some Zuerich parking lots.

Zuerich: add missing capacities and coords

---

original/heilbronn.geojson
original/heilbronn.py

This PR fixes the currently failing Heilbronn scraper. I.e.,
* it fixes the failing last updated parsing
* it skips two incomplete lot records 
* it updates some lot infos (e.g. missing lots, url/coord/has_live_capacity infos)

Heilbronn: update srcaper and geojson

---

original/hanau.geojson
original/hanau.py

This PR fixes public_url/source_url for the (apparently just moved) Hanau parking website.
Besides this, it updates the public_url and capacity of Hanau Parkhaus City-Center.

Hanau: fix urls and update geojson

---

original/luebeck.py

This PR fixes the Lübeck scraper, which failed as div with classname `free-spots` was missing as parking is closed.

Luebeck: fixes unexpectedly closed parking lot

---

original/hamburg.geojson
original/hamburg.py
schema.json
util/strings.py

This PR updates the hamburg scraper and adds hamburg.json. 
Further, it adds "straßenrand" to guess_lot_type and maps this to "street".
Note: schema.json did not contain `street` as supported lot_type, a further commit fixes this. However, I assume that this does not cause any backward compatibility issue(?)

Hamburg: updates scraper and geojson

---

original/heidelberg.geojson
original/heidelberg.py

This PR fixes Heidelberg.get_lot_infos and updates the geojson.
Note: the scraped public_url of `P16 Nordbrückenkopf` is broken. I fixed it manually to the correct url.

Heidelberg: fix scraper.get_lot_infos and update geojson

---

original/freiburg.geojson
original/freiburg.py

This PR updates capacity information and uses the coordinates provided by Freiburg's WFS

Freiburg: Add missing coords and update capacity

---

original/apag.geojson
original/apag.py

This PR fixes apag (parking provider Aachener Parkhaus GmbH) scraper and geojson.
Note: apag includes the cities of Aachen, Würselen, Dülmen, Datteln and even a parking in Berlin (East Side Mall).

Aachen: update apag scraper and geojson

---

original/rosenheim.geojson
original/rosenheim.py

This PR updates Rosenheim scraper and geojson.
However, two questions came up:
* I'm not aware of the conventions regarding backward compatibility. In `rosenheim.get_lot_infos()` I currently still request v1 lot_info information but don't use it. Only currently via source_url retrievable lot information is returned. How should these be merged? Should old parking lots still be returned and with which ID? the new one converted to the legacy ID?
* rosenheim publishes two publications, one providing static lot information, one dynamic occupancy data. Both are linked via an external, numeric id, which currently can't be persisted via `LotInfo`. This is a scenario, which I expect to become a lot more usual, especially for cities publishing DATEXII publications. IMHO, LotInfo should be extended …

Update rosenheim scraper and geojson

---

original/wiesbaden.geojson
original/wiesbaden.py
util/strings.py

This PR updates the Wiesbaden scraper and geojson:
* The public_url has moved to https://www.wiesbaden.de/leben-in-wiesbaden/verkehr/auto/parken/parkhaeuser.php
* Parking lot "PH Galeria Kaufhof" was added
* scraping was failing, as `Status` has been moved from a `td` to a `th/h3`
* additionally, the `PH Luisenforum` request is currently failing (see screenshot below). I informed the Imprint contact who forwarded the issue to the responsible person. The scraper is now a bit more robust and ignores such issues.

Update wiesbaden scraper and geojson

---

original/mannheim.geojson
original/mannheim.py

This PR updates `mannheim` scraper and geojson.
i.e.
* it excludes apparently invalid parkings from the results
* it updates `has_live_capacity` information
* it removes no longer existing parking `Nationaltheater`
* it maps `Hauptbahnhof P3 Parkhaus` to legacy `Hauptbahnhof P3/P4, Parkhaus` to keep the history and data

Mannheim: update scraper and geojson

---

original/koeln.py

This PR checks, if the timestamp property is actually not null before parsing it.

Fix koeln scraper

---

original/muenster.geojson
original/muenster.py

This PR updates muenster scraper and geojson.
i.e., 
* it includes the table, as it's exclusion skippe the last parking
* in `muenster.get_lot_infos` adds minimally required lot info for yet unknown parking lots
* it adds missing parking lots to the geojson
* updates manually set capacity and has_live_data

Muenster: update scraper and geojson

---

util/structs.py

Adds `to_dict()` in Struct base class to have a defined method to access this data in further data processing.

add to_dict() for structs

---

common/base_converter/base_converter.py
common/models.py
requirements.txt
test-push-converter.py
v3/vrs_p_r.py

This MR adds the ability to add more result details to v3 converters. It also fixes some minor issues like ignoring empty lines at Excel Import or the missing LXML package for XML imports.

More result details, minor enhancements

---

original/heilbronn.py
util/structs.py

Fixes a complete crash at heilbronn if GeoJSON and scraped information have different datasets. Adds error messages to the result, too, in order to use / log them later.

prevent heilbronn crash

---

original/karlsruhe.py

There were invalid chars (protected whitespace) in HTML.

remove-invalid-chars-at-karlsruhe

---

v3/reutlingen.py

uid is a string, and postgre does not int instead of str as input for a string field

fix reutlingen uid typing

---

new/aachen.geojson
new/aachen.py
pyproject.toml
util/strings.py

This PR adds parkings in Aachen, retrieved from the official Mobilithek DATEX2 datasets for static and dynamic parkings. 
The static DATEX2 feed does not provide address and url information

Add DATEX2 source for Aachen
